/**
 * Register für den Speichercode.
 * WICHTIG: Nur hinten anfügen, nie umsortieren oder löschen – sonst werden alte
 * Speichercodes aus den Heftern ungültig. Nicht mehr genutzte Einträge bleiben stehen.
 */
export const MAP_IDS = ['alex_zimmer', 'kabelitz', 'wohnzimmer', 'briefzentrum', 'dorfplatz', 'museum', 'dorfladen', 'knotenburg', 'gymnasium'] as const;

export const ITEM_IDS = [
  'netzblick_v1',
  'brief',
  'briefmarke',
  'zettel_funkstille',
  'binaer_karte',
  'block_fernbedienung',
  'schluessel_kvz',
  'restauriertes_foto',
  'kabelbinder',
  'usb_stick',
  // Kapitel 2
  'netzblick_v2',
  'fremder_stick',
  'schluessel7',
] as const;

export const FLAG_IDS = [
  // M0 (Testversion)
  'intro_gesehen',
  'ping_dabei',
  'paket_geoeffnet',
  'netzblick_erklaert',
  'opa_begruesst',
  'kvz_gesehen',
  // Kapitel 1
  'prolog_gesehen',
  'mama_gesprochen',
  'idee_brief',
  'brief_geschrieben',
  'marke_erhalten',
  'brief_eingeworfen',
  'tag2',
  'krause_getroffen',
  'paket_erhalten',
  'briefzentrum_fertig',
  'zurueck_zuhause',
  'brille_gebaut',
  'netz_defekt_gesehen',
  'scan_erklaert',
  'zettel_gefunden',
  'kvz_repariert',
  'papa_gesprochen',
  'router_gesehen',
  // Kapitel 1, M2a
  'kowalski_auftrag',
  'froehlich_gesprochen',
  'schloss1',
  'schloss2',
  'schloss3',
  'pixelwand_geloest',
  'geheimtext_geloest',
  'binaer_gelernt',
  'foto_restauriert',
  'exp_schickard',
  'exp_pascal',
  'exp_leibniz',
  'exp_lovelace',
  'exp_zuse',
  'exp_turing',
  'exp_neumann',
  'pioniere_belohnt',
  'emil_gesprochen',
  'kruemel_programmiert',
  'kruemel_repariert',
  'schluessel_gefunden',
  'schacht_gesehen',
  'fernschreiber_gesehen',
  'foto_auftrag',
  // Kapitel 1, M2b
  'laden_zu_gesehen',
  'tag3',
  'nguyen_gesprochen',
  'pfand_repariert',
  'terminal_gesehen',
  'haendler_gesprochen',
  'haendler_bonus',
  'lehmann_gesprochen',
  'dateien_fertig',
  'tabelle_fertig',
  'kabelbinder_gekauft',
  'kabelsalat_fertig',
  'email_gesendet',
  'tag4',
  'lina_da',
  'plakat_fertig',
  'nacht',
  'kapitel1_fertig',
  'geburtstag_gefeiert',
  // Kapitel 2, M3a
  'k2_start',
  'k2_ada_update',
  'k2_knotenburg',
  'k2_work_gesprochen',
  'k2_algorithmus',
  'k2_clientserver',
  'k2_kanal_auftrag',
  'k2_kanal1',
  'k2_kanal2',
  'k2_stick_abgegeben',
  'k2_zuhause',
  'k2_schacht',
] as const;

export const LEXICON_IDS = [
  'kabel',
  'kabelverzweiger',
  'information_daten',
  'uebertragung',
  'eva',
  'betriebssystem',
  'objekt',
  'binaerzahlen',
  'bilder_als_zahlen',
  'text_als_zahlen',
  'pioniere',
  'algorithmus',
  'zustandsdiagramm',
  'farbkanaele',
  'einheiten',
  'uebertragungsrate',
  'dateitypen',
  'tabellenkalkulation',
  'pixel_vektor',
  'inhalt_design',
  // Kapitel 2 (Klasse 8)
  'algorithmus_eigenschaften',
  'client_server',
  'wiederholung',
  'verzweigung',
  'funk',
] as const;

export const QUEST_IDS = [
  'm0_zimmer',
  'm0_draussen',
  'm0_kabel',
  'm0_fertig',
  'q1_mama',
  'q1_lina',
  'q1_brief',
  'q1_marke',
  'q1_einwerfen',
  'q1_tuer',
  'q1_sortieren',
  'q1_paket',
  'q1_brille',
  'q1_kasten',
  'q1_fortsetzung',
  'q1_kowalski',
  'q1_museum',
  'q1_archiv',
  'q1_zurueck_kowalski',
  'q1_emil',
  'q1_gully',
  'q1_kabelbinder',
  'q1_schlafen',
  'q1_bytes',
  'q1_kaufen',
  'q1_reparatur',
  'q1_email',
  'q1_samstag',
  'q1_fest',
  'q1_kapitel_ende',
  // Kapitel 2
  'k2_ada',
  'k2_bus',
  'k2_schule',
  'k2_clientserver',
  'k2_kanal',
  'k2_stick',
  'k2_heim',
  'k2_fortsetzung',
] as const;

export type MapId = (typeof MAP_IDS)[number];
export type ItemId = (typeof ITEM_IDS)[number];
export type FlagId = (typeof FLAG_IDS)[number];
export type LexiconId = (typeof LEXICON_IDS)[number];
export type QuestId = (typeof QUEST_IDS)[number];
