/**
 * Register für den Speichercode.
 * WICHTIG: Nur hinten anfügen, nie umsortieren oder löschen – sonst werden alte
 * Speichercodes aus den Heftern ungültig. Nicht mehr genutzte Einträge bleiben stehen.
 */
export const MAP_IDS = ['alex_zimmer', 'kabelitz', 'wohnzimmer', 'briefzentrum', 'dorfplatz', 'museum', 'dorfladen', 'knotenburg', 'gymnasium', 'bibliothek', 'fernmeldeamt', 'netzleitstelle', 'silberbach', 'silberstollen', 'werkstatt', 'weltkarte', 'frankfurt', 'landestation', 'island', 'tokio', 'sydney', 'opas_keller'] as const;

export const ITEM_IDS = [
  'netzblick_v1',
  'brief',
  'briefmarke',
  'zettel_funkstille',
  'binaer_karte',
  'block_fernbedienung',
  'schluessel_kvz',
  'restauriertes_foto',
  'kabelbinder',
  'usb_stick',
  // Kapitel 2
  'netzblick_v2',
  'fremder_stick',
  'schluessel7',
  'echtheitslupe',
  'caesar_scheibe',
  'taubenfeder',
  // Kapitel 3
  'netzblick_v3',
  'schluesselpaar',
  'grubenlampe',
  // Kapitel 4
  'postkarte',
  'quelltext_linse',
  'reisepass',
  // Kapitel 5
  'netzblick_v4',
  'subnetzmaske',
  'traceroute_kompass',
] as const;

export const FLAG_IDS = [
  // M0 (Testversion)
  'intro_gesehen',
  'ping_dabei',
  'paket_geoeffnet',
  'netzblick_erklaert',
  'opa_begruesst',
  'kvz_gesehen',
  // Kapitel 1
  'prolog_gesehen',
  'mama_gesprochen',
  'idee_brief',
  'brief_geschrieben',
  'marke_erhalten',
  'brief_eingeworfen',
  'tag2',
  'krause_getroffen',
  'paket_erhalten',
  'briefzentrum_fertig',
  'zurueck_zuhause',
  'brille_gebaut',
  'netz_defekt_gesehen',
  'scan_erklaert',
  'zettel_gefunden',
  'kvz_repariert',
  'papa_gesprochen',
  'router_gesehen',
  // Kapitel 1, M2a
  'kowalski_auftrag',
  'froehlich_gesprochen',
  'schloss1',
  'schloss2',
  'schloss3',
  'pixelwand_geloest',
  'geheimtext_geloest',
  'binaer_gelernt',
  'foto_restauriert',
  'exp_schickard',
  'exp_pascal',
  'exp_leibniz',
  'exp_lovelace',
  'exp_zuse',
  'exp_turing',
  'exp_neumann',
  'pioniere_belohnt',
  'emil_gesprochen',
  'kruemel_programmiert',
  'kruemel_repariert',
  'schluessel_gefunden',
  'schacht_gesehen',
  'fernschreiber_gesehen',
  'foto_auftrag',
  // Kapitel 1, M2b
  'laden_zu_gesehen',
  'tag3',
  'nguyen_gesprochen',
  'pfand_repariert',
  'terminal_gesehen',
  'haendler_gesprochen',
  'haendler_bonus',
  'lehmann_gesprochen',
  'dateien_fertig',
  'tabelle_fertig',
  'kabelbinder_gekauft',
  'kabelsalat_fertig',
  'email_gesendet',
  'tag4',
  'lina_da',
  'plakat_fertig',
  'nacht',
  'kapitel1_fertig',
  'geburtstag_gefeiert',
  // Kapitel 2, M3a
  'k2_start',
  'k2_ada_update',
  'k2_knotenburg',
  'k2_work_gesprochen',
  'k2_algorithmus',
  'k2_clientserver',
  'k2_kanal_auftrag',
  'k2_kanal1',
  'k2_kanal2',
  'k2_stick_abgegeben',
  'k2_zuhause',
  'k2_schacht',
  // Kapitel 2, M3b
  'k2_dienstag',
  'k2b_stick',
  'k2b_mail',
  'k2b_adressen',
  'k2b_ipmac',
  'k2b_pakete',
  'k2b_phishing',
  'k2b_hilfe_berger',
  'k2b_hilfe_passant',
  'k2b_hilfe_jonas',
  'k2b_rathaus',
  'k2b_passwort',
  'k2b_pino',
  'k2b_zuhause',
  // Kapitel 2, M3c
  'k2_mittwoch',
  'k2c_fakefoto',
  'k2c_suche',
  'k2c_bild',
  'k2c_metadaten',
  'k2c_lange',
  'k2c_mobbing',
  'k2c_kollaboration',
  'k2c_scheibe',
  'k2c_caesar',
  'k2c_fma_offen',
  'k2c_domains',
  'k2c_filter',
  'kapitel2_fertig',
  // Kapitel 3
  'k3_start',
  'k3_ada',
  'k3_heimnetz',
  'k3_cam',
  'k3_opa',
  'k3_yilmaz',
  'k3_pakete',
  'k3_wlan',
  'k3_daten',
  'k3_ki',
  'k3_tag2',
  'k3_kalle',
  'k3_raum1',
  'k3_raum2',
  'k3_raum3',
  'k3_raum4',
  'k3_raum5',
  'k3_boss',
  'kapitel3_fertig',
  // Kapitel 4
  'k4_start',
  'k4_postkarte',
  'k4_kevin',
  'k4_kruemel',
  'k4_robotik',
  'k4_html',
  'k4_regex',
  'k4_chat',
  'k4_bus',
  'k4_stimme',
  'k4_emil',
  'kapitel4_fertig',
  // Kapitel 5 und Finale
  'k5_start',
  'k5_frankfurt',
  'k5_seekabel',
  'k5_island',
  'k5_tokio',
  'k5_sydney',
  'k5_leon',
  'k5_nacht',
  'k5_keller',
  'k5_raum_adressen',
  'k5_raum_schluessel',
  'k5_raum_maschinen',
  'k5_raum_wahrheit',
  'k5_streit',
  'k5_stecker',
  'spiel_ende',
] as const;

export const LEXICON_IDS = [
  'kabel',
  'kabelverzweiger',
  'information_daten',
  'uebertragung',
  'eva',
  'betriebssystem',
  'objekt',
  'binaerzahlen',
  'bilder_als_zahlen',
  'text_als_zahlen',
  'pioniere',
  'algorithmus',
  'zustandsdiagramm',
  'farbkanaele',
  'einheiten',
  'uebertragungsrate',
  'dateitypen',
  'tabellenkalkulation',
  'pixel_vektor',
  'inhalt_design',
  // Kapitel 2 (Klasse 8)
  'algorithmus_eigenschaften',
  'client_server',
  'wiederholung',
  'verzweigung',
  'funk',
  'email',
  'adressen',
  'ip_mac',
  'datenpakete',
  'phishing',
  'passwort',
  'brute_force',
  'personenbezogen',
  'suchmaschinen',
  'ki_bilder',
  'metadaten',
  'kollaboration',
  'cybermobbing',
  'verschluesselung',
  // Kapitel 3 (Klasse 9)
  'heimnetz',
  'pan_lan_wan',
  'zwei_faktor',
  'tcp_ip',
  'routing',
  'p2p',
  'protokolle',
  'asymmetrisch',
  'datenbank',
  'sql',
  'big_data',
  'ki_lernen',
  'uebertragungsmedien',
  'switch_router',
  'dns',
  'nachhaltigkeit',
  // Kapitel 4 (Klasse 10)
  'datentypen',
  'bedingungen',
  'unterprogramme',
  'fehlermeldungen',
  'robotik',
  'html',
  'barrierefreiheit',
  'css',
  'regex',
  'syntax_semantik',
  'client_server_dienst',
  'suchen_sortieren',
  'maschinen_entscheiden',
  'zeitabhaengige_medien',
  // Kapitel 5 (Oberstufe)
  'topologien',
  'ipv4_ipv6',
  'dhcp',
  'subnetting',
  'routingtabellen',
  'lichtwellenleiter',
  'paketvermittlung',
  'vpn',
  'schutzziele',
  'backup',
  'hash',
  'blockchain',
  'steganografie',
  'dns_hierarchie',
  'zeichenkodierung',
  'tls',
  'zertifikate',
  'social_engineering',
  'kryptoanalyse',
  'webtechnologien',
  'traceroute',
] as const;

export const QUEST_IDS = [
  'm0_zimmer',
  'm0_draussen',
  'm0_kabel',
  'm0_fertig',
  'q1_mama',
  'q1_lina',
  'q1_brief',
  'q1_marke',
  'q1_einwerfen',
  'q1_tuer',
  'q1_sortieren',
  'q1_paket',
  'q1_brille',
  'q1_kasten',
  'q1_fortsetzung',
  'q1_kowalski',
  'q1_museum',
  'q1_archiv',
  'q1_zurueck_kowalski',
  'q1_emil',
  'q1_gully',
  'q1_kabelbinder',
  'q1_schlafen',
  'q1_bytes',
  'q1_kaufen',
  'q1_reparatur',
  'q1_email',
  'q1_samstag',
  'q1_fest',
  'q1_kapitel_ende',
  // Kapitel 2
  'k2_ada',
  'k2_bus',
  'k2_schule',
  'k2_clientserver',
  'k2_kanal',
  'k2_stick',
  'k2_heim',
  'k2_fortsetzung',
  'k2b_schule',
  'k2b_markt',
  'k2b_rathaus',
  'k2b_pino',
  'k2b_heim',
  'k2c_bibliothek',
  'k2c_lange',
  'k2c_schule',
  'k2c_zettel',
  'k2c_schluessel',
  'k2c_fernmeldeamt',
  'k2_kapitel_ende',
  'k3_ada',
  'k3_router',
  'k3_opa',
  'k3_leitstelle',
  'k3_wlan',
  'k3_datenbank',
  'k3_schlafen',
  'k3_stollen',
  'k3_tiefer',
  'k3_kapitel_ende',
  'k4_werkstatt',
  'k4_html',
  'k4_regex',
  'k4_chat',
  'k4_stimme',
  'k4_kapitel_ende',
  'k5_frankfurt',
  'k5_seekabel',
  'k5_island',
  'k5_tokio',
  'k5_sydney',
  'k5_heim',
  'k5_taubenschlag',
  'k5_keller',
  'k5_opa',
  'k5_ende',
] as const;

export type MapId = (typeof MAP_IDS)[number];
export type ItemId = (typeof ITEM_IDS)[number];
export type FlagId = (typeof FLAG_IDS)[number];
export type LexiconId = (typeof LEXICON_IDS)[number];
export type QuestId = (typeof QUEST_IDS)[number];
