/** Anzeigenamen der Sprecher im Dialogfenster. */
export const SPEAKERS: Record<string, string> = {
  ping: 'Ping',
  opa: 'Opa Werner',
  ada: 'Tante Ada',
  mama: 'Mama',
  papa: 'Papa',
  alex: 'Alex',
  krause: 'Frau Krause',
  oezdemir: 'Herr Özdemir',
  morse: 'Morse',
  kowalski: 'Herr Kowalski',
  froehlich: 'Frau Fröhlich',
  emil: 'Emil',
  kruemel: 'Krümel',
  nguyen: 'Herr Nguyen',
  haendler: 'Händler Hubert',
  lehmann: 'Frau Lehmann',
  lina: 'Lina',
  funkstille: 'FUNKSTILLE',
  work: 'Herr Work',
  mia: 'Mia',
  jonas: 'Jonas',
  fahrer: 'Busfahrerin',
  passant: 'Passant',
  pino: 'Pino',
  lange: 'Bäcker Lange',
  schulz: 'Frau Schulz',
  berger: 'Frau Berger',
  weber: 'Frau Weber',
  sommer: 'Frau Sommer',
  yilmaz: 'Dr. Yilmaz',
  kalle: 'Kalle',
  kevin: 'Kevin',
  schubert: 'Herr Schubert',
  leon: 'Leon',
  sato: 'Frau Sato',
  sigrun: 'Sigrun',
  kapitaenin: 'Kapitänin Moreau',
  unbekannt: '???',
  // Figuren ohne feste Aufgabe
  joggerin: 'Joggerin',
  bello: 'Bello',
  rentner: 'Herr Pfeifer',
  kind_a: 'Paula',
  kind_b: 'Malik',
  marktfrau: 'Marktfrau',
  ente: 'Ente',
  musiker: 'Straßenmusiker',
  skater: 'Skater',
  bote: 'Paketbote',
  touristin: 'Touristin',
  hausmeister: 'Hausmeister Kunze',
  leserin: 'Leserin',
  wanderer: 'Wanderer',
  reisende: 'Reisende',
  fischer: 'Fischer',
  surferin: 'Surferin',
  kunde: 'Kunde',
};
