/** Anzeigenamen der Sprecher im Dialogfenster. */
export const SPEAKERS: Record<string, string> = {
  ping: 'Ping',
  opa: 'Opa Werner',
  ada: 'Tante Ada',
  mama: 'Mama',
  papa: 'Papa',
  alex: 'Alex',
  krause: 'Frau Krause',
  oezdemir: 'Herr Özdemir',
  morse: 'Morse',
  kowalski: 'Herr Kowalski',
  froehlich: 'Frau Fröhlich',
  emil: 'Emil',
  kruemel: 'Krümel',
  nguyen: 'Herr Nguyen',
  haendler: 'Händler Hubert',
  lehmann: 'Frau Lehmann',
  lina: 'Lina',
  funkstille: 'FUNKSTILLE',
  unbekannt: '???',
};
