import type { MapDef } from '../../engine/world/MapDef';
import { choice, give, lexicon, minigame, narrate, quest, say, setFlag, when } from '../../engine/script/Script';

export const alexZimmer: MapDef = {
  id: 'alex_zimmer',
  name: 'Alex\' Zimmer',
  outside: '#1a1c2c',
  legend: {
    W: 'innenwand', I: 'innenfenster', _: 'dielen', t: 'teppich', M: 'fussmatte',
    k: 'kalender', B: 'bett_o', b: 'bett_u', D: 'schreibtisch', C: 'computer', R: 'regal', P: 'pflanze',
  },
  ground: [
    'WWIWWWWIWW',
    '__________',
    '__________',
    '___tttt___',
    '___tttt___',
    '__________',
    '__________',
    '____M_____',
  ],
  deco: [
    '    k     ',
    'B     DCRP',
    'b         ',
    '          ',
    '          ',
    '          ',
    '          ',
    '          ',
  ],
  entities: [
    { kind: 'warp', x: 4, y: 7, to: { map: 'wohnzimmer', x: 1, y: 1, dir: 'down' } },
    {
      kind: 'interact',
      id: 'kalender',
      x: 4,
      y: 0,
      script: [{ op: 'calendar' }],
      scan: { name: 'schulkalender', klasse: 'Kalender', attribute: [['monat', 'September'], ['markiert', 'Samstag: Geburtstag!']], methoden: ['umblaettern'] },
    },
    {
      kind: 'interact',
      id: 'schreibtisch',
      x: 6,
      y: 1,
      script: [
        when(
          { flag: 'brief_geschrieben' },
          [narrate('Hier hast du den Brief an Lina geschrieben. Ein paar leere Umschläge liegen noch da.')],
          [
            when(
              { flag: 'idee_brief' },
              [
                narrate('Papier, Stift, Umschläge – alles da. Los geht\'s!'),
                minigame('brief'),
                give('brief'),
                setFlag('brief_geschrieben'),
                say('ping', 'Auf dem Papier stehen jetzt nur Striche und Kringel – das sind Daten.'),
                say('ping', 'Erst wenn Lina sie liest und versteht, werden daraus Informationen: Geburtstag, Samstag, 15 Uhr, bei dir. Gurr!'),
                lexicon('information_daten'),
                say('ping', 'Jetzt fehlt nur noch eine Briefmarke. Wer hat denn so was heute noch?'),
                quest('q1_marke'),
              ],
              [narrate('Dein Schreibtisch. Stifte, Papier und ein paar leere Umschläge.')],
            ),
          ],
        ),
      ],
    },
    {
      kind: 'interact',
      id: 'computer',
      x: 7,
      y: 1,
      script: [
        narrate('Dein Computer. „Keine Internetverbindung" steht in der Ecke. Speichern geht aber trotzdem.'),
        { op: 'save' },
      ],
      scan: {
        name: 'computer',
        klasse: 'Computer',
        attribute: [['bildschirm', '24 Zoll'], ['farbe', 'schwarz'], ['internet', 'keine Verbindung']],
        methoden: ['starten', 'speichern', 'herunterfahren'],
      },
    },
    {
      kind: 'interact',
      id: 'bett',
      x: 0,
      y: 1,
      script: [narrate('Dein Bett. Noch fünf Minuten …? Nein – es gibt zu tun!')],
      scan: { name: 'bett', klasse: 'Bett', attribute: [['farbe', 'blau'], ['laenge', '2 m']], methoden: [] },
    },
    { kind: 'interact', id: 'bett2', x: 0, y: 2, script: [narrate('Dein Bett. Noch fünf Minuten …? Nein – es gibt zu tun!')] },
    {
      kind: 'interact',
      id: 'regal',
      x: 8,
      y: 1,
      script: [narrate('Bücher über Tauben, über den Weltraum – und eins mit dem Titel „Wie funktioniert das Internet?". Noch ungelesen.')],
      scan: { name: 'regal', klasse: 'Regal', attribute: [['anzahlBuecher', '23'], ['material', 'Holz']], methoden: [] },
    },
    { kind: 'interact', id: 'fenster1', x: 2, y: 0, script: [narrate('Draußen liegt Kabelitz in der Sonne.')] },
    { kind: 'interact', id: 'fenster2', x: 7, y: 0, script: [narrate('Nebenan sieht man Opa Werners Taubenschlag und seine große Antenne.')] },
    {
      kind: 'interact',
      id: 'paket',
      x: 8,
      y: 4,
      tile: 'paket',
      visibleIf: { flag: 'paket_erhalten' },
      scan: { name: 'paket', klasse: 'Paket', attribute: [['absender', 'Tante Ada, Frankfurt'], ['gewicht', '1,2 kg'], ['inhalt', 'leer']], methoden: ['oeffnen'] },
      script: [
        when(
          { flag: 'brille_gebaut' },
          [narrate('Das leere Paket von Tante Ada. Ping sitzt gern darin.')],
          [
            narrate('Das Paket von Tante Ada! Darin: ein Brillengestell, viele winzige Bauteile und ein Brief.'),
            say('ada', 'Hallo Alex! Hier ist ein Prototyp, an dem ich gerade arbeite: eine Brille, die Unsichtbares sichtbar macht – Kabel, Geräte, Daten.'),
            say('ada', 'Ich habe sie extra nicht fertig zusammengebaut. Wenn du sie selbst baust, verstehst du, wie sie funktioniert.'),
            say('ada', 'Alles Gute schon mal zum Geburtstag! Deine Tante Ada'),
            minigame('eva'),
            lexicon('eva'),
            give('netzblick_v1'),
            setFlag('brille_gebaut'),
            say('ping', 'Gurr! Eine Brille, die Daten sieht? Setz sie draußen auf – mit der Taste N!'),
            quest('q1_brille'),
          ],
        ),
      ],
    },
  ],
  onEnter: [
    when({ not: { flag: 'intro_gesehen' } }, [
      say('ping', 'Ping! Guten Morgen, Alex!'),
      say('ping', 'Mit den Pfeiltasten oder W A S D läufst du herum. Mit Leertaste oder Enter sprichst du mit Leuten und untersuchst Dinge.'),
      say('ping', 'Wenn du nicht weiterweißt, drück H. Dann helfe ich dir – dafür bin ich da!'),
      say('ping', 'Mit M öffnest du das Menü. Und der Kalender an der Wand? Da blätterst du ins nächste Schuljahr – aber nur mit dem Code deiner Lehrkraft.'),
      choice('Alles klar?', [
        ['Alles klar!', [say('ping', 'Prima! Gurr!')]],
        ['Nochmal langsam …', [say('ping', 'Laufen: Pfeiltasten. Reden: Leertaste. Hilfe: H. Menü: M. Du schaffst das!')]],
      ]),
      narrate('Von unten ruft jemand:'),
      say('mama', 'Aaaalex! Kommst du mal runter? Das Internet ist weg!'),
      setFlag('intro_gesehen'),
      setFlag('ping_dabei'),
      quest('q1_mama'),
    ]),
  ],
};
