import type { MapDef } from '../../engine/world/MapDef';
import { interlude, lexicon, minigame, narrate, quest, say, setFlag, warp, when } from '../../engine/script/Script';

export const briefzentrum: MapDef = {
  id: 'briefzentrum',
  name: 'Briefzentrum Knotenburg',
  outside: '#1a1c2c',
  legend: { W: 'hallenwand', _: 'beton', G: 'tor', F: 'fach', B: 'band', K: 'briefkiste', m: 'maschine_l', n: 'maschine_r' },
  ground: [
    'WWWWWWWWWWWWWW',
    '______________',
    '______________',
    '______________',
    '______________',
    '______________',
    '______________',
    '______________',
    '_______G______',
  ],
  deco: [
    '              ',
    ' FFFFF  FFFFF ',
    '              ',
    '      mn      ',
    '              ',
    ' BBBB    BBBB ',
    '              ',
    '  K        K  ',
    '              ',
  ],
  entities: [
    {
      kind: 'npc',
      id: 'krause',
      sprite: 'krause',
      x: 5,
      y: 6,
      dir: 'down',
      script: [
        when(
          { flag: 'briefzentrum_fertig' },
          [say('krause', 'Danke nochmal! Ich bring dich gleich heim.')],
          [
            say('krause', 'Willkommen im Briefzentrum Knotenburg! Hier kommen alle Briefe aus der Gegend an und werden sortiert, bevor wir sie ausfahren.'),
            say('krause', 'Normalerweise liest die Maschine die Postleitzahlen und sortiert blitzschnell. Heute sind wir die Maschine!'),
            minigame('sortieren'),
            say('krause', 'Super gemacht! Ohne dich wären wir heute nicht fertig geworden.'),
            say('krause', 'Weißt du, was jetzt mit deinem Brief passiert? Ich zeig\'s dir.'),
            minigame('briefreise'),
            lexicon('uebertragung'),
            say('ping', 'Zwei Tage und drei Stunden für einen Brief … Gurr. Das dauert ganz schön!'),
            say('krause', 'So, ich bring dich wieder heim.'),
            setFlag('briefzentrum_fertig'),
            interlude('Am Nachmittag bringt Frau Krause dich zurück nach Kabelitz.'),
            setFlag('zurueck_zuhause'),
            warp('kabelitz', 6, 8, 'down'),
            say('ping', 'Da wartet doch noch ein Paket auf dich! Gurr!'),
            quest('q1_paket'),
          ],
        ),
      ],
    },
    {
      kind: 'npc',
      id: 'oezdemir',
      sprite: 'oezdemir',
      x: 10,
      y: 3,
      dir: 'down',
      script: [
        say('oezdemir', 'Die Maschine zeigt nur: „Keine Verbindung zum Server". Seit heute Nacht. Komisch, oder?'),
        say('oezdemir', 'Ohne Verbindung weiß sie nicht, welcher Bezirk welche Postleitzahlen hat. Also machen wir es wie früher: von Hand.'),
      ],
    },
    { kind: 'interact', id: 'maschine', x: 6, y: 3, script: [narrate('Die große Sortiermaschine. Auf dem Bildschirm blinkt: „FEHLER – keine Verbindung".')] },
    { kind: 'interact', id: 'maschine2', x: 7, y: 3, script: [narrate('Die große Sortiermaschine. Auf dem Bildschirm blinkt: „FEHLER – keine Verbindung".')] },
    { kind: 'interact', id: 'faecher', x: 3, y: 1, script: [narrate('Hunderte Fächer, jedes mit einer Postleitzahl beschriftet.')] },
    { kind: 'interact', id: 'faecher2', x: 10, y: 1, script: [narrate('Hunderte Fächer, jedes mit einer Postleitzahl beschriftet.')] },
    { kind: 'interact', id: 'kiste', x: 2, y: 7, script: [narrate('Eine Kiste voller Briefe, die noch sortiert werden müssen.')] },
    { kind: 'interact', id: 'kiste2', x: 11, y: 7, script: [narrate('Eine Kiste voller Briefe, die noch sortiert werden müssen.')] },
    {
      kind: 'trigger',
      id: 'ausgang',
      x: 7,
      y: 8,
      activeIf: { not: { flag: 'briefzentrum_fertig' } },
      script: [say('krause', 'Halt, halt! Erst wird sortiert, dann fahren wir heim.'), { op: 'turn', dir: 'up' }],
    },
  ],
};
