import type { MapDef } from '../../engine/world/MapDef';
import { narrate, say, setFlag, when } from '../../engine/script/Script';

export const dorfplatz: MapDef = {
  id: 'dorfplatz',
  name: 'Dorfplatz Kabelitz',
  outdoor: true,
  legend: {
    '.': 'gras', ',': 'gras2', '=': 'weg', p: 'pflaster',
    T: 'baum_ol', Y: 'baum_or', U: 'baum_ul', I: 'baum_ur', b: 'busch',
    '<': 'dach_l', '^': 'dach_m', '>': 'dach_r', '[': 'traufe_l', _: 'traufe_m', ']': 'traufe_r',
    '(': 'wand_l', w: 'wand_m', ')': 'wand_r', F: 'fenster', D: 'tuer',
    M: 'museumsschild', K: 'kabelschacht', L: 'laterne', B: 'bank',
  },
  ground: [
    '....,.....,....=..............',
    '.......,..,....=...,..,.......',
    '....,..........=,............,',
    '..........,....=............,.',
    '....,,.........=.,...........,',
    '......,........=,......,......',
    '....,........,.=..,...,...,...',
    ',....=.........=......=.....,.',
    '.,.pppppppppppppppppppppppp...',
    '...pppppppppppppppppppppppp...',
    '..,pppppppppppppppppppppppp...',
    '.............,................',
    '.,....................,.......',
    ',....,........................',
    '..,.,....,............,..,,...',
    '..............................',
  ],
  deco: [
    'TYbbbbbbbbbbbbb bbbbbbbbbbbbTY',
    'UI                          UI',
    'TY                          TY',
    'UI<^^^^^>           <^^^>   UI',
    'TY<^^^^^>           <^^^>   TY',
    'UI[_____] K         [___]   UI',
    'TY(FwDwF)           (FDF)   TY',
    'UI     M                    UI',
    'TY                          TY',
    'UI L                      L UI',
    'TY                          TY',
    'UI                          UI',
    'TY         B      B         TY',
    'UI    b                b    UI',
    '                              ',
    '  bbbbbbbbbbbbbbbbbbbbbbbbbb  ',
  ],
  extraSolid: [[22, 6]],
  entities: [
    { kind: 'warp', x: 15, y: 0, to: { map: 'kabelitz', x: 15, y: 18, dir: 'up' } },
    { kind: 'warp', x: 5, y: 6, to: { map: 'museum', x: 3, y: 7, dir: 'up' } },
    {
      kind: 'interact',
      id: 'museumsschild',
      x: 7,
      y: 7,
      script: [narrate('„Dorfmuseum Kabelitz – Von der Rechenuhr zum Computer. Eintritt frei!"')],
    },
    {
      kind: 'interact',
      id: 'laden_tuer',
      x: 22,
      y: 6,
      script: [
        narrate('Ein Zettel an der Tür: „Heute wegen Inventur geschlossen. Morgen wieder da! – Herr Nguyen"'),
        when({ flag: 'schluessel_gefunden' }, [
          say('ping', 'Mist, ausgerechnet heute! Dann müssen wir wiederkommen. Gurr …'),
          narrate('Ende der Testversion M2a. Wie es mit Kabelbindern, Bytes und dem Dorffest weitergeht, erfährst du in der nächsten Version!'),
        ]),
      ],
    },
    {
      kind: 'interact',
      id: 'kabelschacht',
      x: 10,
      y: 5,
      script: [
        when(
          { flag: 'kruemel_repariert' },
          [
            narrate('Ein langer, verwinkelter Kabelschacht. Krümel würde hineinpassen – aber der Weg ist viel länger als 10 Befehle.'),
            say('ping', 'Dafür bräuchte man einen Trick, damit Krümel Befehle wiederholt … Gurr. Merken wir uns!'),
            setFlag('schacht_gesehen'),
          ],
          [narrate('Ein Kabelschacht mit Deckel. Innen ist es eng und dunkel.')],
        ),
      ],
      scan: { name: 'kabelschacht', klasse: 'Schacht', attribute: [['laenge', 'ca. 40 m'], ['inhalt', 'Kabel']], methoden: ['oeffnen'] },
    },
    {
      kind: 'interact',
      id: 'bank',
      x: 11,
      y: 12,
      script: [narrate('Eine Bank. Hier sitzen die Leute beim Dorffest und essen Kuchen.')],
    },
  ],
};
