import type { MapDef } from '../../engine/world/MapDef';
import { lexicon, narrate, quest, say, setFlag, when } from '../../engine/script/Script';

export const kabelitz: MapDef = {
  id: 'kabelitz',
  name: 'Kabelitz',
  legend: {
    '.': 'gras', ',': 'gras2', '=': 'weg', '*': 'blumen', '#': 'strasse', '~': 'strasse_mitte',
    T: 'baum_ol', Y: 'baum_or', U: 'baum_ul', I: 'baum_ur', b: 'busch', z: 'zaun',
    '<': 'dach_l', '^': 'dach_m', '>': 'dach_r', '[': 'traufe_l', _: 'traufe_m', ']': 'traufe_r',
    '(': 'wand_l', w: 'wand_m', ')': 'wand_r', F: 'fenster', D: 'tuer',
    S: 'schild', P: 'briefkasten', K: 'verteilerkasten', A: 'antenne', O: 'taubenschlag_o', Q: 'taubenschlag_u',
  },
  ground: [
    '....,.........................',
    '.................,,...........',
    '......,.......,.....,.........',
    '.....,,.....**.,,...,.........',
    '..,.....,......,..............',
    '...........,...,....,......,.,',
    '..............,,....**..,.....',
    '.............,......*........,',
    '.....,=.........=.............',
    '......=.......,,=.............',
    '..*...=.........=....,........',
    ',.**..=.........=........,..,.',
    '......=.........=.........,.,.',
    '......=.........=.......=,....',
    '==============================',
    '==============================',
    '##############################',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '##############################',
    '...,.........,...............,',
  ],
  deco: [
    'TYTYTYTYTYTYTYTYTYTYTYTYTYTYTY',
    'UIUIUIUIUIUIUIUIUIUIUIUIUIUIUI',
    'TY                          TY',
    'UI                       z  UI',
    'TY  <^^^>     <^^^>  A O z  TY',
    'UI  <^^^>     <^^^>    Q z  UI',
    'TY  [___]     [___]      z  TY',
    'UI  (FDF)     (FDF)      z  UI',
    'TY                 zzz zzz  TY',
    'UI       TY           <^^^> UI',
    'TY       UI  b     b  <^^^> TY',
    'UI                 b  [___] UI',
    'TY                    (FDF) TY',
    'UI S       K       P        UI',
    'b                             ',
    'b                             ',
    'b                             ',
    'b                             ',
    'b                             ',
    'bbb bb bb bb bb bb bb bb bb bb',
  ],
  extraSolid: [
    [16, 7],
    [24, 12],
  ],
  entities: [
    { kind: 'warp', x: 6, y: 7, to: { map: 'alex_zimmer', x: 4, y: 6, dir: 'up' } },
    {
      kind: 'npc',
      id: 'opa',
      sprite: 'opa',
      x: 17,
      y: 9,
      dir: 'down',
      script: [
        when(
          { flag: 'opa_begruesst' },
          [
            when(
              { item: 'netzblick_v1' },
              [
                say('opa', 'Was hast du denn da für \'ne Brille, Kind? Sieht aus wie aus\'m Fernsehen.'),
                say('opa', 'Na ja … Hauptsache, du setzt sie auch mal ab und guckst dir die echte Welt an. Hehe.'),
              ],
              [say('opa', 'Früher, da hat man sich noch Briefe geschrieben. Mit Briefmarke und allem. Das war noch was!')],
            ),
          ],
          [
            say('opa', 'Na, Alex! Schon wach? Ping hat mich heute früh schon besucht, die olle Taube.'),
            say('opa', 'Die fliegt immer noch zu meinem Taubenschlag. Kann eben nicht vergessen, wo sie herkommt.'),
            say('ping', 'Gurr …'),
            setFlag('opa_begruesst'),
          ],
        ),
      ],
    },
    { kind: 'interact', id: 'opa_tuer', x: 16, y: 7, script: [narrate('Opa Werners Haustür. Abgeschlossen – Opa ist ja draußen.')] },
    { kind: 'interact', id: 'emil_tuer', x: 24, y: 12, script: [narrate('Hier wohnt Emil mit seinen Eltern. Niemand öffnet.')] },
    { kind: 'interact', id: 'schild', x: 3, y: 13, script: [narrate('„Kabelitz – Bitte fahren Sie vorsichtig."')] },
    { kind: 'interact', id: 'briefkasten', x: 19, y: 13, script: [narrate('Ein gelber Briefkasten. „Leerung: 17:00 Uhr".')] },
    { kind: 'interact', id: 'antenne', x: 21, y: 4, script: [narrate('Eine große Antenne in Opa Werners Garten. „Für den Wetterbericht", sagt Opa immer.')] },
    { kind: 'interact', id: 'taubenschlag', x: 23, y: 5, script: [narrate('Opa Werners Taubenschlag. An der Tür ist ein Tastenfeld: „Nur für Tauben". Seltsam …')] },
    {
      kind: 'interact',
      id: 'verteilerkasten',
      x: 11,
      y: 13,
      script: [
        when(
          { item: 'netzblick_v1' },
          [
            narrate('Mit der Brille siehst du es: Aus jedem Haus im Dorf läuft ein Kabel hierher!'),
            narrate('Und aus dem Kasten führt eine dicke Leitung weiter Richtung Stadt.'),
            say('ping', 'Gurr! Hier laufen alle Kabel von Kabelitz zusammen. Deshalb stehen diese grauen Kästen überall!'),
            lexicon('kabelverzweiger'),
            setFlag('kvz_gesehen'),
            quest('m0_fertig'),
            narrate('Du hast das Ende der Testversion erreicht. In Kapitel 1 geht es richtig los!'),
          ],
          [narrate('Ein grauer Kasten. Die stehen überall herum – aber was ist da eigentlich drin?')],
        ),
      ],
    },
    {
      kind: 'trigger',
      id: 'ortsausgang',
      x: 29,
      y: 15,
      script: [say('ping', 'Da geht es nach Knotenburg. Aber das kommt erst später. Gurr!'), { op: 'turn', dir: 'left' }],
    },
  ],
  net: {
    devices: [
      { id: 'alex', x: 5, y: 7, label: 'Heimnetz Familie' },
      { id: 'opa', x: 15, y: 7, label: 'Haus Lösch' },
      { id: 'emil', x: 23, y: 12, label: 'Haus Emil' },
      { id: 'kvz', x: 11, y: 13, label: 'Kabelverzweiger' },
      { id: 'stadt', x: 29, y: 15, label: 'Richtung Knotenburg' },
    ],
    cables: [
      { from: 'alex', to: 'kvz', medium: 'kupfer', path: [[5, 7], [5, 14], [11, 14], [11, 13]] },
      { from: 'opa', to: 'kvz', medium: 'kupfer', path: [[15, 7], [15, 14], [11, 14], [11, 13]] },
      { from: 'emil', to: 'kvz', medium: 'kupfer', path: [[23, 12], [23, 14], [11, 14], [11, 13]] },
      { from: 'kvz', to: 'stadt', medium: 'glasfaser', path: [[11, 13], [11, 15], [29, 15]] },
    ],
  },
};
