import type { MapDef } from '../../engine/world/MapDef';
import { choice, give, interlude, lexicon, minigame, narrate, quest, say, setFlag, warp, when, type Script } from '../../engine/script/Script';
import { bergerScript, bibTuer, fmaTuer, jonasDienstag, langeScript, passantDienstag, pinoScript, schulzScript } from '../dialog/kapitel2b';

/** Mit dem Bus zurück nach Kabelitz. */
const heimfahrt: Script = [interlude('Mit dem Bus zurück nach Kabelitz …'), warp('kabelitz', 27, 15, 'down')];

const kanal: Script = [
  when(
    { flag: 'k2_kanal2' },
    [narrate('Die Klappe zum Kabelkanal. Hier hat Krümel den fremden USB-Stick gefunden.')],
    [
      when(
        { not: { flag: 'k2_kanal_auftrag' } },
        [narrate('Eine Klappe in der Schulmauer: „Kabelkanal – Zugang nur für Technik". Drinnen ist es eng und dunkel.')],
        [
          when({ not: { flag: 'k2_kanal1' } }, [
            narrate('Du öffnest die Klappe und setzt Krümel in den Kabelkanal.'),
            say('ping', 'Der Gang steigt an wie eine Treppe: vor, rechts, vor, links … immer wieder dasselbe!'),
            say('ping', 'Mit dem neuen Knopf ⟳ kann Krümel Blöcke wiederholen. Alles bis zum ⟲ Ende wird so oft ausgeführt, wie du einstellst.'),
            minigame('bloecke:kanal1'),
            lexicon('wiederholung'),
            setFlag('k2_kanal1'),
            say('ping', 'Vier Treppenstufen mit nur sieben Blöcken! Gurr!'),
          ]),
          narrate('Hinter der Treppe biegt der Kanal um eine Ecke. Wie lang die Gänge sind, sieht man von hier nicht.'),
          say('ping', 'Krümel muss selbst merken, wann er abbiegen soll. Dafür gibt es den Block „? wenn Wand: ↱" – wenn vorne eine Wand ist, dreht Krümel rechts, sonst nicht.'),
          minigame('bloecke:kanal2'),
          lexicon('verzweigung'),
          setFlag('k2_kanal2'),
          narrate('Krümel kommt zurück. Zwischen den Bürsten klemmt ein kleiner schwarzer USB-Stick.'),
          give('fremder_stick'),
          narrate('Auf dem Stick klebt ein Aufkleber: eine durchgestrichene Antenne.'),
          say('ping', 'D-das Zeichen von FUNKSTILLE! Hier in Knotenburg?! Den bringen wir sofort zu Herrn Work – aber nicht einstecken!'),
          quest('k2_stick'),
        ],
      ),
    ],
  ),
];

export const knotenburg: MapDef = {
  id: 'knotenburg',
  name: 'Knotenburg',
  outdoor: true,
  legend: {
    '.': 'gras', ',': 'gras2', p: 'pflaster', '=': 'weg', '#': 'strasse', '~': 'strasse_mitte',
    T: 'baum_ol', Y: 'baum_or', U: 'baum_ul', I: 'baum_ur', b: 'busch',
    '<': 'dach_l', '^': 'dach_m', '>': 'dach_r', '[': 'traufe_l', _: 'traufe_m', ']': 'traufe_r',
    '(': 'wand_l', w: 'wand_m', ')': 'wand_r', F: 'fenster', D: 'tuer',
    '!': 'schild', S: 'schulschild', K: 'kabelschacht', L: 'laterne', B: 'bank', H: 'bushalt', V: 'verteilerkasten',
  },
  ground: [
    '....,.........,.,....,..,.....',
    '.....,............,.........,.',
    '....,..............,..........',
    ',,,......,,......,...,.......,',
    '.................,...,..,.....',
    '....,.........................',
    '..pppppppppppppppppppppppppp..',
    '..pppppppppppppppppppppppppp..',
    '..pppppppppppppppppppppppppp..',
    '..pppppppppppppppppppppppppp..',
    '..pppppppppppppppppppppppppp.,',
    '.,pppppppppppppppppppppppppp..',
    '.............pppp.......,.....',
    '..,,........,pppp.,.,.........',
    '.........,,..pppp.............',
    '..,..........pppp.............',
    '==============================',
    '##############################',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '##############################',
  ],
  deco: [
    'TYTYTYTYTYTYTYTYTYTYTYTYTYTYTY',
    'UIUIUIUIUIUIUIUIUIUIUIUIUIUIUI',
    'TY<^^^>  <^^^^^^^^^^>  <^^^>TY',
    'UI<^^^>  <^^^^^^^^^^>  <^^^>UI',
    'TY[___]  [__________]  [___]TY',
    'UI(FDF)  (FwFwDwFwFw)  (FDF)UI',
    'TY    !     S     K   !     TY',
    'UI      L            L      UI',
    'TY                          TY',
    'UI                          UI',
    'TY         B      B         TY',
    'UI                          UI',
    'TY <^^^>            <^^^^^> TY',
    'UI <^^^>  b        b<^^^^^> UI',
    'TY [___]  b        b[_____] TY',
    'UI (FDF)!         V (FwDwF)!UI',
    '  H                           ',
    '                              ',
    '                              ',
    '                              ',
  ],
  extraSolid: [
    [4, 5],
    [25, 5],
    [5, 15],
    [23, 15],
  ],
  entities: [
    { kind: 'warp', x: 14, y: 5, to: { map: 'gymnasium', x: 2, y: 8, dir: 'up' } },
    {
      kind: 'interact',
      id: 'bushalt',
      x: 2,
      y: 16,
      script: [
        when(
          { flag: 'k2_zuhause' },
          [choice('Mit dem Bus nach Kabelitz fahren?', [['Ja, nach Hause', heimfahrt], ['Nein, noch bleiben', []]])],
          [
            when(
              { flag: 'k2_stick_abgegeben' },
              heimfahrt,
              [narrate('Bushaltestelle „Knotenburg Markt". Der nächste Bus nach Kabelitz fährt erst nach Schulschluss.')],
            ),
          ],
        ),
      ],
    },
    {
      kind: 'interact',
      id: 'rathaus',
      x: 4,
      y: 5,
      script: [narrate('Das Rathaus von Knotenburg. „Bürgeramt: Mo–Fr 8–12 Uhr". Heute Vormittag ist es voll.')],
    },
    { kind: 'interact', id: 'rathausschild', x: 6, y: 6, script: [narrate('„Rathaus Knotenburg – Bürgeramt, Standesamt, Stadtverwaltung"')] },
    {
      kind: 'interact',
      id: 'pizzeria',
      x: 25,
      y: 5,
      script: [narrate('Pizzeria „Da Pino". An der Tür: „Neu! Bestellen mit unserer App!" Geöffnet ab 11:30 Uhr.')],
    },
    { kind: 'interact', id: 'pizzaschild', x: 22, y: 6, script: [narrate('„Da Pino – die beste Pizza in Knotenburg. Jetzt auch per App!"')] },
    { kind: 'interact', id: 'bibliothek', x: 5, y: 15, script: bibTuer },
    { kind: 'interact', id: 'bibschild', x: 8, y: 15, script: [narrate('„Stadtbibliothek Knotenburg – Bücher, Zeitungen, Internet-Plätze"')] },
    {
      kind: 'interact',
      id: 'fernmeldeamt',
      x: 23,
      y: 15,
      script: fmaTuer,
      scan: { name: 'fernmeldeamt', klasse: 'Gebäude', attribute: [['baujahr', '1928'], ['zustand', 'stillgelegt']], methoden: ['oeffnen (verschlossen)'] },
    },
    { kind: 'interact', id: 'fmaschild', x: 27, y: 15, script: [narrate('„Ehemaliges Fernmeldeamt Knotenburg. Betreten verboten!"')] },
    {
      kind: 'interact',
      id: 'schulschild',
      x: 12,
      y: 6,
      script: [narrate('„Gymnasium Knotenburg". Darunter hat jemand einen Zettel geklebt: „WLAN-Passwort ändert sich jede Woche!"')],
    },
    { kind: 'interact', id: 'kanal', x: 18, y: 6, script: kanal, scan: { name: 'kabelkanal', klasse: 'Kanal', attribute: [['inhalt', 'Netzwerkkabel'], ['ziel', 'Serverraum']], methoden: ['oeffnen'] } },
    {
      kind: 'interact',
      id: 'kvz_stadt',
      x: 18,
      y: 15,
      script: [narrate('Ein grauer Kasten wie der in Kabelitz. Dieser hier ist heil – zum Glück.')],
      scan: { name: 'kabelverzweiger', klasse: 'Kabelverzweiger', attribute: [['ort', 'Markt'], ['zustand', 'in Ordnung']], methoden: ['verbinden'] },
    },
    {
      kind: 'npc',
      id: 'passant',
      sprite: 'passant',
      x: 6,
      y: 9,
      dir: 'down',
      script: [
        when({ flag: 'k2b_phishing' }, passantDienstag, [
        say('passant', 'Hast du das gehört? In Kabelitz war letztes Jahr tagelang das Internet weg. Sabotage, sagen die Leute!'),
        say('passant', 'Hier in Knotenburg passiert so was zum Glück nicht. Hier ist alles vernetzt: Schule, Rathaus, sogar die Pizzeria.'),
        ]),
      ],
    },
    {
      kind: 'npc',
      id: 'jonas_markt',
      sprite: 'jonas',
      x: 17,
      y: 8,
      dir: 'left',
      visibleIf: { all: [{ flag: 'k2_stick_abgegeben' }, { not: { flag: 'k2_mittwoch' } }] },
      script: [
        when({ flag: 'k2b_phishing' }, jonasDienstag, [
          say('jonas', 'Hey Alex! Ich hab heute schon wieder so eine Mail bekommen: „Ihr Konto wird gesperrt!" Voll gruselig. Bis morgen!'),
        ]),
      ],
    },
    { kind: 'npc', id: 'berger', sprite: 'berger', x: 9, y: 9, dir: 'down', visibleIf: { flag: 'k2_dienstag' }, script: bergerScript },
    { kind: 'npc', id: 'schulz', sprite: 'schulz', x: 3, y: 6, dir: 'down', visibleIf: { flag: 'k2_dienstag' }, script: schulzScript },
    { kind: 'npc', id: 'pino', sprite: 'pino', x: 24, y: 6, dir: 'down', visibleIf: { flag: 'k2_dienstag' }, script: pinoScript },
    { kind: 'npc', id: 'lange', sprite: 'lange', x: 21, y: 9, dir: 'down', visibleIf: { flag: 'k2_mittwoch' }, script: langeScript },
    { kind: 'interact', id: 'backstand', x: 22, y: 9, tile: 'backstand', visibleIf: { flag: 'k2_mittwoch' }, script: langeScript },
  ],
  onEnter: [
    when({ not: { flag: 'k2_knotenburg' } }, [
      setFlag('k2_knotenburg'),
      say('ping', 'Knotenburg! So viele Häuser, so viele Leute. Und so viele Kabel unter dem Pflaster!'),
      say('ping', 'Setz mal deine Brille auf (N)! Siehst du die rosa Ringe um die Schule? Das sind Funkwellen vom WLAN.'),
      say('ping', 'Daten reisen nicht nur durch Kabel. Handys und Laptops bekommen sie auch per Funk – ganz ohne Kabel.'),
      lexicon('funk'),
      say('ping', 'Das Gymnasium ist das große Haus da oben. Los, sonst kommst du am ersten Tag zu spät!'),
      quest('k2_schule'),
    ]),
  ],
  net: {
    devices: [
      { id: 'schule', x: 14, y: 5, label: 'Gymnasium' },
      { id: 'rathaus', x: 4, y: 5, label: 'Rathaus' },
      { id: 'pino', x: 25, y: 5, label: 'Da Pino' },
      { id: 'bib', x: 5, y: 15, label: 'Bibliothek' },
      { id: 'kvz', x: 18, y: 15, label: 'Kabelverzweiger' },
      { id: 'kabelitz', x: 0, y: 17, label: 'Richtung Kabelitz' },
    ],
    cables: [
      { from: 'schule', to: 'kvz', medium: 'glasfaser', path: [[14, 5], [14, 12], [18, 12], [18, 15]] },
      { from: 'rathaus', to: 'kvz', medium: 'kupfer', path: [[4, 5], [4, 7], [12, 7], [12, 12], [18, 12], [18, 15]] },
      { from: 'pino', to: 'kvz', medium: 'kupfer', path: [[25, 5], [25, 7], [18, 7], [18, 15]] },
      { from: 'bib', to: 'kvz', medium: 'kupfer', path: [[5, 15], [5, 16], [18, 16], [18, 15]] },
      { from: 'kvz', to: 'kabelitz', medium: 'glasfaser', path: [[18, 15], [18, 17], [0, 17]] },
    ],
    funk: [
      { x: 14, y: 3, reichweite: 5, label: 'WLAN Gymnasium' },
      { x: 25, y: 3, reichweite: 3, label: 'WLAN „Pino-Gast"' },
    ],
  },
};
