import type { MapDef } from '../../engine/world/MapDef';
import { zielFrankfurt, zielIsland, zielKabelitz, zielLandestation, zielSydney, zielTokio } from '../dialog/kapitel5';

/** Die Weltkarte: Von hier aus reisen Alex und Tante Ada zu den Knoten des Internets. */
export const weltkarte: MapDef = {
  id: 'weltkarte',
  name: 'Weltkarte',
  outside: '#29366f',
  legend: { '~': 'meer', '.': 'land', e: 'eis', r: 'route', O: 'ortsmarke' },
  ground: [
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '~~~~~~~~ee~~~~~~~~~~~~~~~~~~~~',
    '~.....~~eer~~~~~~.........~~~~',
    '~.....~~~rr...............~~~~',
    '~.....~~~~~...............~.~~',
    '~.....~~~~~...............r.~~',
    '~.....~~~~~...............~.~~',
    '~.....~~~~~...............~.~~',
    '~~~....~~~~~~~~~~.........~r~~',
    '~~~....~~~~~~~~~~~~~~~~~~~~r~~',
    '~~~....~~~~~~~~~~~~~~~~~~~~r~~',
    '~~~....~~~~~~~~~~~~~~~......~~',
    '~~~....~~~~~~~~~~~~~~~......~~',
    '~~~....~~~~~~~~~~~~~~~......~~',
    '~~~~~~~~~~~~~~~~~~~~~~......~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
  ],
  deco: [
    '                              ',
    '        O                     ',
    '                              ',
    '                              ',
    '            O    O         O  ',
    '                              ',
    '                              ',
    '           O                  ',
    '                              ',
    '                              ',
    '                              ',
    '                              ',
    '                              ',
    '                          O   ',
    '                              ',
    '                              ',
  ],
  entities: [
    { kind: 'interact', id: 'ziel_frankfurt', x: 12, y: 4, script: zielFrankfurt, scan: { name: 'frankfurt', klasse: 'Internetknoten', attribute: [['daten', 'über 10 Terabit/s'], ['land', 'Deutschland']], methoden: ['austauschen'] } },
    { kind: 'interact', id: 'ziel_kabelitz', x: 17, y: 4, script: zielKabelitz },
    { kind: 'interact', id: 'ziel_landestation', x: 11, y: 7, script: zielLandestation },
    { kind: 'interact', id: 'ziel_island', x: 8, y: 1, script: zielIsland },
    { kind: 'interact', id: 'ziel_tokio', x: 27, y: 4, script: zielTokio },
    { kind: 'interact', id: 'ziel_sydney', x: 26, y: 13, script: zielSydney },
  ],
  // Mit der Brille v4 „Weltsicht": Namen der Knoten und die großen Leitungen um den Globus
  net: {
    devices: [
      { id: 'ffm', x: 12, y: 4, label: 'Frankfurt' },
      { id: 'kab', x: 17, y: 4, label: 'Kabelitz' },
      { id: 'atl', x: 11, y: 7, label: 'Atlantik-Station' },
      { id: 'isl', x: 8, y: 1, label: 'Island' },
      { id: 'tok', x: 27, y: 4, label: 'Tokio' },
      { id: 'syd', x: 26, y: 13, label: 'Sydney' },
      { id: 'ame', x: 3, y: 5, label: 'Amerika' },
    ],
    cables: [
      { from: 'kab', to: 'ffm', medium: 'glasfaser', path: [[17, 4], [12, 4]] },
      { from: 'ffm', to: 'atl', medium: 'glasfaser', path: [[12, 4], [12, 7], [11, 7]] },
      { from: 'atl', to: 'ame', medium: 'glasfaser', path: [[11, 7], [3, 7], [3, 5]] },
      { from: 'ffm', to: 'isl', medium: 'glasfaser', path: [[12, 4], [9, 4], [9, 1], [8, 1]] },
      { from: 'ffm', to: 'tok', medium: 'glasfaser', path: [[12, 4], [12, 3], [27, 3], [27, 4]] },
      { from: 'tok', to: 'syd', medium: 'glasfaser', path: [[27, 4], [28, 4], [28, 13], [26, 13]] },
    ],
  },
};
